permalink: /blog/:title
# Information required for feed
title: Sakura Jekyll # Change this to your site name.
description:
url:
author:

date_format: "%b %d, %Y"

defaults:
  -
    scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "post"


# Third-party services
# just leave empty to disable it
google_analytics:
disqus_shortname:
twitter:
    username:

# Includes an icon in the 'ABOUT' page for each username you enter
footer-links:
  dribbble:
  email:
  facebook:
  flickr:
  github:
  instagram:
  linkedin:
  pinterest:
  rss: True # just type anything here for a working RSS icon
  twitter:
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: # channel/<your_long_string> or user/<user-name>
  googleplus: # anything in your profile username that comes after plus.google.com/

gems:
    - jekyll-sitemap
    - jekyll-feed
    - jekyll-seo-tag
